/* eslint-disable @typescript-eslint/no-unused-vars */
import { MigrationInterface, QueryRunner } from 'typeorm';

export class FakePosts1625502714797 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`insert into post (title, text, "originalPosterId") values ('Bison bison', 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.', 1);
    insert into post (title, text, "originalPosterId") values ('unavailable', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 1);
    insert into post (title, text, "originalPosterId") values ('Macropus eugenii', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 1);
    insert into post (title, text, "originalPosterId") values ('Phalacrocorax carbo', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', 1);
    insert into post (title, text, "originalPosterId") values ('Merops sp.', 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.', 1);
    insert into post (title, text, "originalPosterId") values ('Spermophilus armatus', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 1);
    insert into post (title, text, "originalPosterId") values ('Arctogalidia trivirgata', 'Nulla nisl.', 1);
    insert into post (title, text, "originalPosterId") values ('Phoenicopterus ruber', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.', 1);
    insert into post (title, text, "originalPosterId") values ('Turtur chalcospilos', 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', 1);
    insert into post (title, text, "originalPosterId") values ('Macropus agilis', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 1);
    insert into post (title, text, "originalPosterId") values ('Cordylus giganteus', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 1);
    insert into post (title, text, "originalPosterId") values ('Merops nubicus', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 1);
    insert into post (title, text, "originalPosterId") values ('Scolopax minor', 'In quis justo. Maecenas rhoncus aliquam lacus.', 1);
    insert into post (title, text, "originalPosterId") values ('Aquila chrysaetos', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.', 1);
    insert into post (title, text, "originalPosterId") values ('Colobus guerza', 'Pellentesque ultrices mattis odio. Donec vitae nisi.', 1);
    insert into post (title, text, "originalPosterId") values ('Zalophus californicus', 'Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.', 1);
    insert into post (title, text, "originalPosterId") values ('Panthera leo persica', 'Quisque porta volutpat erat.', 1);
    insert into post (title, text, "originalPosterId") values ('Coluber constrictor', 'Suspendisse potenti. Nullam porttitor lacus at turpis.', 1);
    insert into post (title, text, "originalPosterId") values ('Bettongia penicillata', 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', 1);
    insert into post (title, text, "originalPosterId") values ('Threskionis aethiopicus', 'Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.', 1);
    insert into post (title, text, "originalPosterId") values ('Felis silvestris lybica', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 1);
    insert into post (title, text, "originalPosterId") values ('Scolopax minor', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis.', 1);
    insert into post (title, text, "originalPosterId") values ('Kobus defassa', 'Aenean sit amet justo. Morbi ut odio.', 1);
    insert into post (title, text, "originalPosterId") values ('Grus canadensis', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.', 1);
    insert into post (title, text, "originalPosterId") values ('Pseudoleistes virescens', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 1);
    insert into post (title, text, "originalPosterId") values ('Dasyurus maculatus', 'Pellentesque viverra pede ac diam.', 1);
    insert into post (title, text, "originalPosterId") values ('Eudromia elegans', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.', 1);
    insert into post (title, text, "originalPosterId") values ('Anthropoides paradisea', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', 1);
    insert into post (title, text, "originalPosterId") values ('Phascogale tapoatafa', 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.', 1);
    insert into post (title, text, "originalPosterId") values ('Bison bison', 'Praesent blandit. Nam nulla.', 1);
    insert into post (title, text, "originalPosterId") values ('Ctenophorus ornatus', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.', 1);
    insert into post (title, text, "originalPosterId") values ('Canis lupus', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', 1);
    insert into post (title, text, "originalPosterId") values ('Sus scrofa', 'Fusce consequat. Nulla nisl.', 1);
    insert into post (title, text, "originalPosterId") values ('Ceratotherium simum', 'Quisque id justo sit amet sapien dignissim vestibulum.', 1);
    insert into post (title, text, "originalPosterId") values ('Chauna torquata', 'Integer ac neque. Duis bibendum.', 1);
    insert into post (title, text, "originalPosterId") values ('Bubalus arnee', 'Etiam justo. Etiam pretium iaculis justo.', 1);
    insert into post (title, text, "originalPosterId") values ('Heloderma horridum', 'Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.', 1);
    insert into post (title, text, "originalPosterId") values ('Colobus guerza', 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 1);
    insert into post (title, text, "originalPosterId") values ('Zalophus californicus', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.', 1);
    insert into post (title, text, "originalPosterId") values ('Bubulcus ibis', 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 1);
    insert into post (title, text, "originalPosterId") values ('Macropus robustus', 'Pellentesque ultrices mattis odio. Donec vitae nisi.', 1);
    insert into post (title, text, "originalPosterId") values ('Gyps bengalensis', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 1);
    insert into post (title, text, "originalPosterId") values ('Odocoileus hemionus', 'Integer a nibh.', 1);
    insert into post (title, text, "originalPosterId") values ('Anas punctata', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 1);
    insert into post (title, text, "originalPosterId") values ('Mirounga leonina', 'Vivamus tortor. Duis mattis egestas metus. Aenean fermentum.', 1);
    insert into post (title, text, "originalPosterId") values ('Cynomys ludovicianus', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.', 1);
    insert into post (title, text, "originalPosterId") values ('Ephippiorhynchus mycteria', 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 1);
    insert into post (title, text, "originalPosterId") values ('Amblyrhynchus cristatus', 'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.', 1);
    insert into post (title, text, "originalPosterId") values ('Eolophus roseicapillus', 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 1);
    insert into post (title, text, "originalPosterId") values ('Libellula quadrimaculata', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 1);
    insert into post (title, text, "originalPosterId") values ('Buteo jamaicensis', 'In sagittis dui vel nisl. Duis ac nibh.', 1);
    insert into post (title, text, "originalPosterId") values ('Cebus apella', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 1);
    insert into post (title, text, "originalPosterId") values ('Spizaetus coronatus', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 1);
    insert into post (title, text, "originalPosterId") values ('Manouria emys', 'Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.', 1);
    insert into post (title, text, "originalPosterId") values ('Varanus sp.', 'Vestibulum sed magna at nunc commodo placerat.', 1);
    insert into post (title, text, "originalPosterId") values ('Porphyrio porphyrio', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 1);
    insert into post (title, text, "originalPosterId") values ('Papio cynocephalus', 'Morbi ut odio.', 1);
    insert into post (title, text, "originalPosterId") values ('Streptopelia senegalensis', 'Integer non velit.', 1);
    insert into post (title, text, "originalPosterId") values ('Ctenophorus ornatus', 'Nunc purus. Phasellus in felis. Donec semper sapien a libero.', 1);
    insert into post (title, text, "originalPosterId") values ('Motacilla aguimp', 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', 1);
    insert into post (title, text, "originalPosterId") values ('Uraeginthus granatina', 'Nam dui.', 1);
    insert into post (title, text, "originalPosterId") values ('Spermophilus tridecemlineatus', 'Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 1);
    insert into post (title, text, "originalPosterId") values ('Vulpes chama', 'Nunc nisl.', 1);
    insert into post (title, text, "originalPosterId") values ('Eumetopias jubatus', 'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.', 1);
    insert into post (title, text, "originalPosterId") values ('Alcelaphus buselaphus caama', 'Nulla facilisi.', 1);
    insert into post (title, text, "originalPosterId") values ('Erinaceus frontalis', 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 1);
    insert into post (title, text, "originalPosterId") values ('Lutra canadensis', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.', 1);
    insert into post (title, text, "originalPosterId") values ('Stenella coeruleoalba', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 1);
    insert into post (title, text, "originalPosterId") values ('Spermophilus richardsonii', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 1);
    insert into post (title, text, "originalPosterId") values ('Panthera tigris', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 1);
    insert into post (title, text, "originalPosterId") values ('Galago crassicaudataus', 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 1);
    insert into post (title, text, "originalPosterId") values ('Uraeginthus angolensis', 'Suspendisse potenti. In eleifend quam a odio.', 1);
    insert into post (title, text, "originalPosterId") values ('Sylvicapra grimma', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', 1);
    insert into post (title, text, "originalPosterId") values ('Vulpes chama', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 1);
    insert into post (title, text, "originalPosterId") values ('Ploceus rubiginosus', 'Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.', 1);
    insert into post (title, text, "originalPosterId") values ('Chlidonias leucopterus', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 1);
    insert into post (title, text, "originalPosterId") values ('Pterocles gutturalis', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 1);
    insert into post (title, text, "originalPosterId") values ('Milvus migrans', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 1);
    insert into post (title, text, "originalPosterId") values ('Felis libyca', 'Proin at turpis a pede posuere nonummy.', 1);
    insert into post (title, text, "originalPosterId") values ('Neophoca cinerea', 'Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis.', 1);
    insert into post (title, text, "originalPosterId") values ('Pteronura brasiliensis', 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', 1);
    insert into post (title, text, "originalPosterId") values ('Tockus flavirostris', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', 1);
    insert into post (title, text, "originalPosterId") values ('Columba palumbus', 'Aliquam erat volutpat. In congue.', 1);
    insert into post (title, text, "originalPosterId") values ('Trichoglossus haematodus moluccanus', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 1);
    insert into post (title, text, "originalPosterId") values ('Papio cynocephalus', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 1);
    insert into post (title, text, "originalPosterId") values ('Libellula quadrimaculata', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', 1);
    insert into post (title, text, "originalPosterId") values ('Martes americana', 'Nam tristique tortor eu pede.', 1);
    insert into post (title, text, "originalPosterId") values ('Centrocercus urophasianus', 'Nam dui.', 1);
    insert into post (title, text, "originalPosterId") values ('Lophoaetus occipitalis', 'Donec posuere metus vitae ipsum.', 1);
    insert into post (title, text, "originalPosterId") values ('Pteropus rufus', 'Aliquam sit amet diam in magna bibendum imperdiet.', 1);
    insert into post (title, text, "originalPosterId") values ('Hyaena brunnea', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', 1);
    insert into post (title, text, "originalPosterId") values ('Pteropus rufus', 'Duis bibendum.', 1);
    insert into post (title, text, "originalPosterId") values ('Canis aureus', 'Ut at dolor quis odio consequat varius. Integer ac leo.', 1);
    insert into post (title, text, "originalPosterId") values ('Ramphastos tucanus', 'Aliquam non mauris.', 1);
    insert into post (title, text, "originalPosterId") values ('Boa caninus', 'Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.', 1);
    insert into post (title, text, "originalPosterId") values ('Nyctea scandiaca', 'Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.', 1);
    insert into post (title, text, "originalPosterId") values ('Psophia viridis', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', 1);
    insert into post (title, text, "originalPosterId") values ('Leipoa ocellata', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 1);
    insert into post (title, text, "originalPosterId") values ('Sitta canadensis', 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', 1);
    insert into post (title, text, "originalPosterId") values ('Libellula quadrimaculata', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis.', 1);
    `);
  }

  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  // eslint-disable-next-line @typescript-eslint/naming-convention
  public async down(_: QueryRunner): Promise<void> {}
}
